services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`test.vqndr.nl`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    networks:
      - web
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    networks:
      - web

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  web:
